user: 'hyxpk'
all_hash: '5dfhFff1J7kM47T'
all_aid: 'Xg4pbxt'
all_name: 'hyxpk'
all_title: 'Little Nuns'
all_url: 'https://twitter.com/hyxpk'
subreddit: 'LittleNuns'
database: 'database.db'
table: 'littlenuns'
only_recent: true