user: 'hyxpk'
all_hash: '4qJXaaOjOaLmMED'
all_aid: 'O72a8e3'
all_name: 'hyxpk - Little Nuns'
all_desc: 'Little Nuns art by @hyxpk - https://twitter.com/hyxpk'
subreddit: 'LittleNuns'
database: 'database.db'
table: 'littlenuns'